version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/adnexos.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: adnexos
build:
  run_buildscript: false
images:
  - id: adnexos
    target: service
    service: adnexos
    source: ghcr.io/tametsi/adnexos
    channel: stable
    sort: semver
    tag_regex: '^v?\d+\.\d+\.\d+$'
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
    changelog_locales: [zh, en]
  private:
    enabled: true
    skip_if_version_exists: true
    name: Adnexos
    summary: "无需费力，轻松与朋友在任何情况下分摊开销。"
