name: adnexos

services:
  app:
    image: ghcr.io/tametsi/adnexos:0.9.1
    container_name: 'adnexos'
    restart: unless-stopped
    ports:
       - '8090:8090'
    volumes:
      - pb-data:/app/pb_data
    networks:
      - app_network

volumes:
  pb-data:

networks:
  app_network:
    name: ${NETWORK_NAME}
    external: true
