package: cloud.lazycat.app.adnexos
version: 0.9.1
name: Adnexos
description: "无需费力，轻松与朋友在任何情况下分摊开销。"
min_os_version: "1.5.0"
homepage: https://github.com/tametsi/adnexos
author: tametsi
locales:
  zh:
    description: "无需费力，轻松与朋友在任何情况下分摊开销。"
    name: Adnexos
  en:
    description: "Effortlessly split expenses with friends, in any situation."
    name: Adnexos
